### ISSUE TITLE
Impossible to download invoice

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#189] opened 2018-10-11 11:21 UTC
Strange behavior while downloading invoice - using any other port than 8000 it is impossible! Is this the way it should work?
Configured uwsgi + nginx with ssl, but unfortunately timeout while trying to download invoice PDF file. The same for port 80. Changing port in nginx to 8000 and it works.

**Comment by edwinvandeven** [comment] 2018-10-23 16:57
About the ports; the port shouldn't matter. In production it runs on 80 & 443 without any issues using a socket between uwsgi and nginx. Perhaps you should check your server configuration. 

I seem to be unable to reproduce this behavior for the invoice logo. It behaves as expected in production and in the development branch, leading me to suspect it's an issue with your server configuration.

It's a bit hard to know what exactly the issue is, but perhaps you could check the static files config in nginx for the vhost you configured.

I'm closing this issue, as it doesn't seem to be an OpenStudio issue.

**Closed by edwinvandeven** 2018-10-23 16:57 UTC
Labels: invalid
