### ISSUE TITLE
Usage of organizations option

### ISSUE THREAD

**Issue by Shiva-Bot-Py** [openstudioproject/openstudio#531] opened 2020-11-12 06:05 UTC
Could you please explain usage of organization option. Is organization setup mandatory for use the other options like customer registration, school setup , class creation , payment,?
after setup the organization, where we can use and how we can use the organization option.
Is there any filter options(class ,customer, teacher, employees filter etc.) done with organization...
![Screenshot_2020-11-12 Settings(1)](https://user-images.githubusercontent.com/73157103/98902097-0e393500-24db-11eb-8a49-c42dcd54b6f6.png)

**Comment by edwinvandeven** [comment] 2022-01-06 19:47
One organization is currently required for things like populating the "contact" page in the shop and "From" section of invoices. This organization should be marked as default.
Other than that, there are no real usages for it. It was intended to allow a single OpenStudio instance for multiple organizations sharing a studio, however this was never fully implemented.

**Closed by edwinvandeven** 2022-01-06 19:47 UTC
