### ISSUE TITLE
User with membership can not buy classcard

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#395] opened 2019-04-23 20:56 UTC
Since 2019.01.3 till 2019.3.0 users with membership can not buy classcards that are available only with this membership. Any ideas why? For my installation it is broken since upgrade to 2019.01.3.

**Comment by edwinvandeven** [comment] 2019-04-25 06:35
I just checked in the current master branch, but the issue doesn't seem to be present. I've run all tests and put out release 2019.04.1. Could you upgrade and let me know if the issue is still present?

**Comment by mgailitis** [comment] 2019-04-25 06:58
Maybe it is some kind of DB table relation problem? I can find membership in DB, can see in DB that a classcard is only available with membership.
Sorry for stupid question, but is it still necessary to run https://myopenstudiosite.com/upgrade after upgrading files?
During upgrade to 2019.3.0 had a lot of "duplicate column" and "table already exists" errors.
And one more thing - 2019.1.3 does not work with updated redis. Redis as a service is running, but Openstudio app just doesnt see it - redis.exceptions.ConnectionError.

**Comment by edwinvandeven** [comment] 2019-04-25 09:47
Hmm sounds like there might be a db issue, though I can't be sure as I can't look at it. Or perhaps a mismatch between the table definition files in the /databases folder and the actual state of the tables. 
Yes, it's required to run /upgrade after a version upgrade. It sets the new version so the version in the DB matches the version of the code and it might have some code to update records in the DB where needed to maintain compatability with the code.

Yes it's a known issue that 2019.1.3 doesn't work with updated redis, it's solved in 2019.04.x. The way it connects changed a little bit with a redis update to a new version. For 2019.1.x you need to use redis 2.10.6 from pip to allow it to connect. Later versions don't work.
From 2019.04.x the older version doesn't work.

**Comment by mgailitis** [comment] 2019-04-25 10:33
Can i run this /upgrade on 2019.3.0 running system to find out if it fixes the problem?
How else i could debug this issue?

**Comment by edwinvandeven** [comment] 2019-04-25 11:17
It sounds like there might be a broken migration:
http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#Fixing-broken-migrations

Basically you'd have to manually check if all tables/fields in models/db_tables.py correspond with the actual tables & fields in MySQL.

**Comment by mgailitis** [comment] 2019-04-25 12:33
I upgraded directly from 2019.1.3 to 2019.3.0 without installing 2019.02.4 - maybe there is a problem?
Went through customer_membership relations and data - everything looks correct.

**Comment by edwinvandeven** [comment] 2019-04-26 02:24
I'm not aware of any problems with that upgrade path. I've just upgraded a few installations of 2019.01 to 2019.04 without any error messages. 
Have you checked whether the error persists in 2019.04?

**Comment by mgailitis** [comment] 2019-04-29 09:53
2019.04 fixed the problem! :)

**Closed** 2019-05-15 09:25 UTC
