### ISSUE TITLE
<class 'gluon.contrib.pymysql.err.OperationalError'> (2003, "Can't connect to MySQL server on 'dbserver' ([Errno -3] Temporary failure in name resolution)")

### ISSUE THREAD

**Issue by psp316r** [openstudioproject/openstudio#526] opened 2020-10-30 12:39 UTC
When I have opened the Openstudio i got the following error :

Error ticket for "openstudio"
Ticket ID

127.0.0.1.2020-10-30.17-49-34.1ca65332-61d9-4a1a-812f-9bc56cdff0e3
<class 'gluon.contrib.pymysql.err.OperationalError'> (2003, "Can't connect to MySQL server on 'dbserver' ([Errno -3] Temporary failure in name resolution)")

**Comment by edwinvandeven** [comment] 2020-10-31 21:21
Duplicate of #527

**Closed** 2020-10-31 21:21 UTC
Labels: duplicate
