### ISSUE TITLE
Deprication of SQL command - No_Auto_Create_User (For future release)

### ISSUE THREAD

**Issue by NerdsLogic** [openstudioproject/openstudio#291] opened 2019-01-02 21:54 UTC
The following is output in the terminal console after starting web2py. 

/web2py/gluon/contrib/pymysql/cursors.py:166: Warning: (3090, u"Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.")
  result = self._query(query)

This is probably web2py related.  It was stated that the issue is fixed in the next DAL (https://groups.google.com/forum/#!topic/web2py/gMrRgaz4iUE) but as of 01/02/2018 using the latest version of web2py available, upgrading to MySQL 5.8 could be problem.

**Comment by edwinvandeven** [comment] 2019-01-03 14:22
Yes it looks like we'll have to wait for the next stable Web2py release for this. In case it isn't solved in that release it would be a good idea to askabout it in the w2p google group

**Comment by edwinvandeven** [comment] 2022-01-06 19:51
Seems the web2py framework's lifespan is coming to an end. The developers are putting more effort in other projects now and it looks like MySQL versions > 5.7 won't be supported. 
The issue is resolved though in Costasiella as it's based on Django, which is compatible with MySQL 8 and very recent versions of many other database servers.

**Closed by edwinvandeven** 2022-01-06 19:51 UTC
Labels: wontfix
